### ISSUE TITLE
MNIST with flow.py: negative losses

### ISSUE THREAD

**Issue by jecampagne** [deepmind/distrax#202]
Hello,
I try to use the `flow.py` material in Google Colab nb. Although using
```python
batch_size=128,
 learning_rate=1e-4,
 training_steps=1000,
  eval_frequency=100,
```
I get this val losses
```python
STEP: 0; validation loss: -5.781349182128906
STEP: 100; validation loss: -2047.4188232421875
STEP: 200; validation loss: -2628.3603515625
STEP: 300; validation loss: -2912.349609375
STEP: 400; validation loss: -3038.216552734375
STEP: 500; validation loss: -3087.5771484375
STEP: 600; validation loss: -3074.630859375
STEP: 700; validation loss: -3103.694580078125
STEP: 800; validation loss: -3080.8818359375
STEP: 900; validation loss: -3098.12158203125
``` 
Do I have missed something? Thanks

**Comment by franrruiz** [comment]
This is expected. Note that the flow is defining a probability density function (PDF) $p(x)$ on a **continuous-valued** random variable $x$. As per the definition of the probability density function, we have that $p(x) \geq 0$ and $\int p(x) dx = 1$. Specifically, and unline probability mass functions (PMF), there is _no_ requirement that $p(x)<1$; this may or may not be the case. Thus, the log-likelihood $\log p(x)$ can be either negative or positive, and therefore the same is true for the negative log-likelihood.

**Comment by jecampagne** [comment]
Correct and thanks for the confirmation I was wandering if I have made a bug. sorry.
