### ISSUE TITLE
Create API for conditional flows?

### ISSUE THREAD

**Issue by vz415** [deepmind/distrax#209]
I recently created code for a conditional neural spline flow MNIST example to generate numbers based on class. To do this, I subclassed `MaskedCoupling`, `Inverse`, `Chain`, and `Transformed` to create methods that accepted conditional information, `z`. Here's an example of the `MaskedConditionalCoupling` and its `forward_and_log_det` method with a conditional `z` array:

```python
class MaskedConditionalCoupling(MaskedCoupling):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
    
  def forward_and_log_det(self, x: Array, z: Array) -> Tuple[Array, Array]:
    """Computes y = f(x|z) and log|det J(f)(x|z)|."""
    self._check_forward_input_shape(x)
    masked_x = jnp.where(self._event_mask, x, 0.)
    params = self._conditioner(masked_x, z)
    y0, log_d = self._inner_bijector(params).forward_and_log_det(x)
    y = jnp.where(self._event_mask, x, y0)
    logdet = math.sum_last(
        jnp.where(self._mask, 0., log_d),
        self._event_ndims - self._inner_event_ndims)
    return y, logdet
```

Similarly, I modified all other related classes used to create a neural spline flow to include conditional `z` arrays. 

I think this is a pretty broadly useful area for researchers and was wondering if there are plans to expand bijectors and distributions to handle conditional flows? If not, and there's interest, I'd be happy to contribute my code - subclasses and conditional MNIST example. Although, there may be better ways to extend the API than making new classes for conditional layers, so I'm open to any suggestions. 

For fun, here are conditonal MNIST examples (0-9) from a preliminary run: 
![image](https://user-images.githubusercontent.com/19888961/198847357-c3b182ee-7cf8-4905-bcb0-e3c0aabba45d.png)

**Comment by vz415** [comment]
For anyone interested in this, I made a little repo for conditional flows here: https://github.com/vz415/lfiax.

The plan is to expand it to general likelihood free inference later.

**Comment by tilmantroester** [comment]
I'd just like to second that having the option to pass conditional data would be a great feature to have in distrax.
