### ISSUE TITLE
Gumbel distribution

### ISSUE THREAD

**Issue by mblondel** [deepmind/distrax#21]
It would be great to add the Gumbel distribution.

**Comment by KVROHITH098** [comment]
Hi @mblondel what is the issue?

**Comment by mblondel** [comment]
See #36 for a PR implementing it.

**Comment by freddy123098** [comment]
Ok so I am going to implement this for now and will see the changes later ok.

**Comment by freddy123098** [comment]
Wait for my updates of me fixing this.

**Comment by franrruiz** [comment]
The `Gumbel` distribution is now available in distrax. I'm closing this issue.
