### ISSUE TITLE
Issue with jax version in requirements.txt

### ISSUE THREAD

**Issue by mblondel** [deepmind/distrax#38]
The `requirements.txt` file in the 0.0.1 [tarball release](https://files.pythonhosted.org/packages/03/91/4a5f4206b1d647a910a51f19e8af0454c06547d4d3a1e9693980b17873c8/distrax-0.0.1.tar.gz) on pypi contains this:

```
# Change the sign once TFP is fixed
jax<=0.2.11
```

`<=` is problematic for packages depending both on `distrax` and on a higher version of jax than 0.2.11. If the said TFP issue is fixed, could you release 0.0.2 version of distrax? Thanks!

**Comment by hbq1** [comment]
Resolved in #39. Thanks for the heads-up!
